// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudZ6idAHFuWSgtx51Ffo_QvFpTZlVrCY',
    appId: '1:320312910836:web:ac0e34d19c97ccb67c4fa1',
    messagingSenderId: '320312910836',
    projectId: 'flutter-training-79069',
    authDomain: 'flutter-training-79069.firebaseapp.com',
    storageBucket: 'flutter-training-79069.firebasestorage.app',
    measurementId: 'G-TB40PG8NNX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc6yj8AYq3mWaTaxtm5gEVHz6MfDpTjoc',
    appId: '1:320312910836:ios:1d91b7c2166ea4cc7c4fa1',
    messagingSenderId: '320312910836',
    projectId: 'flutter-training-79069',
    storageBucket: 'flutter-training-79069.firebasestorage.app',
    iosBundleId: 'com.example.flutterTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCudZ6idAHFuWSgtx51Ffo_QvFpTZlVrCY',
    appId: '1:320312910836:web:c91f5ee49084b8db7c4fa1',
    messagingSenderId: '320312910836',
    projectId: 'flutter-training-79069',
    authDomain: 'flutter-training-79069.firebaseapp.com',
    storageBucket: 'flutter-training-79069.firebasestorage.app',
    measurementId: 'G-H44MJG2KRG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc6yj8AYq3mWaTaxtm5gEVHz6MfDpTjoc',
    appId: '1:320312910836:ios:1d91b7c2166ea4cc7c4fa1',
    messagingSenderId: '320312910836',
    projectId: 'flutter-training-79069',
    storageBucket: 'flutter-training-79069.firebasestorage.app',
    iosBundleId: 'com.example.flutterTraining',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnfSV1aqWQTwt7P-wBCe1lBnUcT92fBsg',
    appId: '1:320312910836:android:a412ca1ee2b8a8857c4fa1',
    messagingSenderId: '320312910836',
    projectId: 'flutter-training-79069',
    storageBucket: 'flutter-training-79069.firebasestorage.app',
  );

}